glslangValidator -V object.vert -o object.vert.spv
glslangValidator -V shader.vert -o shader.vert.spv
glslangValidator -V shader.frag -o shader.frag.spv
glslangValidator -V sky.vert -o sky.vert.spv
glslangValidator -V sky.frag -o sky.frag.spv
glslangValidator -V outline.vert -o outline.vert.spv
glslangValidator -V outline.frag -o outline.frag.spv
glslangValidator -V fullscreen.vert -o fullscreen.vert.spv
glslangValidator -V finalize.frag -o finalize.frag.spv
glslangValidator -V object_pass_through.vert -o object_pass_through.vert.spv
glslangValidator -V explode.geom -o explode.geom.spv
glslangValidator -V view_normal.geom -o view_normal.geom.spv
glslangValidator -V view_normal.frag -o view_normal.frag.spv
glslangValidator -V shadow.vert -o shadow.vert.spv
glslangValidator -V shadow.frag -o shadow.frag.spv
glslangValidator -V shadow_point.vert -o shadow_point.vert.spv
glslangValidator -V shadow_point.geom -o shadow_point.geom.spv
glslangValidator -V shadow_point.frag -o shadow_point.frag.spv
glslangValidator -V bloom.frag -o bloom.frag.spv
PAUSE